### ISSUE TITLE
PostgreSQL tagvalues query problem

### ISSUE THREAD

**Issue by haorendashu** [fiatjaf/eventstore#16]
This code:

https://github.com/fiatjaf/eventstore/blob/4c1b0497dfc1bb8050b3d0766322289225364a54/postgresql/query.go#L122

I think should change the ```&&``` to ```@>``` .

**Demos**:
| id | query | result |
| ------ | ------ | ------ |
| demo1 | ARRAY[1,2,3] @> ARRAY[1,2] | true |
| demo2 | ARRAY[1,2,3] @> ARRAY[1,4] | false |
| demo3 | ARRAY[1,2,3] && ARRAY[1,2] | true |
| demo4 | ARRAY[1,2,3] && ARRAY[1,4] | true |

if a filter like this, I think it should query the event contain both ```a``` tag with ```aaa``` value and ```p``` tag with ```ppp``` value, just like ```demo1``` not ```demo4```

```
{
"#a": "aaa",
"#p": "ppp"
}
```

**Comment by fiatjaf** [comment]
I may be missing something, but I think you are correct. This is a bug.
