### ISSUE TITLE
sir

### ISSUE THREAD

**Issue by barrydeen** [fiatjaf/eventstore#31]
2024/09/16 21:35:51 lmdb: value read error (id 88f7879ba48239a6d60169d6a0eee3af7906aa0e05b1cd9f45eec5cd985f3a0d): failed to decode binary: runtime error: slice bounds out of range [:5811] with capacity 693

**Comment by mattn** [comment]
Can you provide full stack trace in your log?

**Comment by fiatjaf** [comment]
I believe this is fixed.
